---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
  namespace: kube-system
provisioner: smb.csi.k8s.io
parameters:
  source: //192.168.1.108/shared
  csi.storage.k8s.io/provisioner-secret-name: windows-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: windows-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
