apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:n3cIvAXQ41LAgiFIY2tDMFcoeabne7jNxm3D/4Ern1gQdl8rqZZdKw==,iv:4mbEQAPuKuZY76ycFFCGC7A92va1l9Z5PAhDwAON2LI=,tag:J0dW29U1/XVOgYOoJoEojw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n7z0aurqmxdk06hyu3ak5nhrp8k6sr2dytz9nd3l98gjqsu0ansmr6v2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcnRBZWNzZlcrcEFwWGxL
            NW9kOHY5MU5xZmpHTFJ1bW1jT0t1dmNGYUNrCjJoMnRXU1E4Y25YUzNETCtmS1FG
            VHBra05Na0JaeDZCUC9LV0FieFhyZ1kKLS0tIG9pRE1OVGlia3JRSWl3WThzZG5I
            OFFRY3JvbWpmV0hoVzdWZTF1MWIxT1UK84OapMM0ouJRPTu6yhzV7k/KsBbna8fw
            fseJZ4i/zVz8CNeZFlR8GIMh7PBgcf87m5r1BYJZhuxDTOML3qXoIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T18:18:46Z"
    mac: ENC[AES256_GCM,data:Bf+0y15kXnO+jXqwLfyzwOk7mh2wGjh9RzaMiPcpsebQHHm+fharWp9/DtCiMJDETOSKtCp9GFjtcTejspn3wkcHzBqK95H9lFG2xrTOlMJsWEjFoT5VwSAKhir8V1/hwS3J12vF71Ji1ijYLOKqAlsDgiycuPu7z8/aNhzoUn8=,iv:Ie/j8Lzsx6YrNYxT7tkg4WSn3EptmAplHIiRJKbeCmU=,tag:MyMC2HTTkF4t1ZgcUuUpWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
