apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:SVL3yI6SiYtnRQ==,iv:4yIr1/edsTXD5KLXIXrnf7wQue8OasgJ1JNStT8+ef0=,tag:JhNtIgjSmRM1nz5f5FSyKQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qf1UMN+5c2DY6CYN6bW0VPxBn9GQ,iv:143ueykLGd4rF11XRXIBxchNTGiClXyPOC3fpKz8Esg=,tag:ZDqFEpHf3sFpvAIzpqqkQw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:2KHLjRc9JcHHT6gwM5U8VVzfwNtB9nxEljRqXSvOrsXXuEF8,iv:b0na/8zHJSRYtwO2kZSrPWGA+1Bl7nw6eZT8KCUe20o=,tag:Yeds//huDXiRWLoI8Glj3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n7z0aurqmxdk06hyu3ak5nhrp8k6sr2dytz9nd3l98gjqsu0ansmr6v2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT3BwTmJLRnQzcisvSnkz
            S0VmaktWOFpab05CUWF5ajMxWU5IR2hla2hNCjJQcTk1ZnMyNU4xeDRhN2wvOU9s
            aU4rdmc0blgyOTJwWnVjY1B2NmovSDAKLS0tIHlDMmRwRUtERlNHMmsxS3M1eXF3
            T3hOZy85bzMza00rT2ZlbDlkYWh3dzQKcHAvZgQ2MghHVyS6GcPv3DT/jjBeYETu
            Icvu37UMIscshdhxuFS+TN0BhfH6xvdgYKXU2Yr5e86pHRExs5/u3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T09:50:46Z"
    mac: ENC[AES256_GCM,data:5qJiQBgJWUiUdlFYp3Tb8g9ptC7BgSKB30rSjdtwssP+3iXZyxx4fQMFG7UnoTs46xybv8mo2DzmQvhHs04PJlMjbkzOn7LQwQ1jNAHjBV6gZrgN9V5dtoApfEwLLTA1lae5DyPCMQsJrjR29YryjJKnyoragJkHZ/79fVGFm7c=,iv:QDIM4rHkM4+HObV/69+dybKiJiGY8UUSR5Phk5LL9Cs=,tag:ohWn7NTDb7PzwXp739oD6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
