apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:R6FFJJhqm9dafoTJG3uKSnbFJRSonlbAg91GOw370RLy1uY5kHNr3w==,iv:43UpyVJ1XxN0nrEpMlBx+WqecNvW5YGZ43+9vAv0OmY=,tag:NID5lI+97HKOwe0OHuGa/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n7z0aurqmxdk06hyu3ak5nhrp8k6sr2dytz9nd3l98gjqsu0ansmr6v2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMlJIMVJPWGI1L0FMbDV1
            RnZROE1GUFVwbFZROXNhL2MvK09RbmFOKzJBCm5CckR4QTdNTW55N3p2alJoanRx
            L1h1dlpaQVM3VDVpUnFPd0owQW5uZEUKLS0tIFVjM3Z0ckJEWGthZ003N3c2YkNj
            dFFYNmlHL2MxNzQyeTBUSVp4dGtLUWsKpUBeTJ76eJcE3DUTECeF4RGIjTl0RWAh
            TlKzgzn4KcwdbjSd+JwoM+CnIpOua7xPwEVYGjLNLz5QCudOzftxfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T09:50:46Z"
    mac: ENC[AES256_GCM,data:a50zH5UdM5sPs7WQ/jXEG6VgzQo2G++iVAauGt95GIbVh+1/JXATl/Xesj46qEy0MDnR6+CsF8PDkJMeXza9hpCMiIq7c68/qnU+0jW8BrI0Si45Iprs5QSTBfl+3aLj87OdAyB2yo9BjItmpoLf39+oD+QOhA77I4ApjTn6w9g=,iv:VrUplm2gw04cpn4Jye3DBlVAETgQclCKq5XI/yNJJN8=,tag:9ZwtZSFFHp3RqMnq3CGx3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
